configName: sam_d10_xmini
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMD10D14AM
projectName: ''
settings:
  PackageFilter: bsp;core;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD10_DFP\2.2.42\atdf\ATSAMD10D14AM.atdf
